name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.22'
          - '5.30'
          - '5.32'
          - '5.34'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: cpm install -g --installdeps
      - name: Run tests
        run: prove -l t
