name: macos
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Perl
        run: brew install perl cpm
      - name: Install Dependencies
        run: cpm install -g
      - name: Run Tests
        run: prove -l t
